config/routes.rb
Rails.application.routes.draw do
  # get 'landing/index'
  root 'pages#home'

  get 'about', to: 'pages#about'

  get 'signup', to: 'users#new'
  
  resources :users, except: [:new]
  resources :products
  resources :categories

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'chat', to: 'chats#index'
  post 'message', to: "messages#create"

  mount ActionCable.server, at: '/cable'

  get 'landing/index'

  resources :carts
  resources :items

  post '/add_to_cart/:product_id', to: 'carts#add_to_cart'
  post 'items/:id/add' => "items#add_quantity", as: "item_add"
  post 'items/:id/reduce' => "items#reduce_quantity", as: "item_reduce"

  resources :orders, only: [:index, :show, :new, :create]

  resources :users do
    member do
      get :confirm_email
    end
  end

end

app/models/User.rb
class User < ApplicationRecord
    before_save {self.email = email.downcase}
    before_save {self.username = username.downcase}
    before_create :confirmation_token

    has_many :messages
    has_one :cart

    # "dependent: :destroy" to destroy dependents.
    # has_many :articles, dependent: :destroy
    validates :username, presence: true, length: { minimum: 3, maximum: 25 }

    validates :password, presence: true, length: { minimum: 4, maximum: 25 }


    #In Ruby, a variable is saved as CONSTANT when saved in All CAPITALS.  
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
                uniqueness: true, length: { maximum: 105 },
                format: {with: VALID_EMAIL_REGEX }
    has_secure_password

    def confirmation_token
        if self.confirm_token.blank?
            self.confirm_token = SecureRandom.urlsafe_base64.to_s
        end
    end

    def email_activate
        self.email_confirmed = true
        self.confirm_token = nil
        save!(:validate => false)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_login, except: [:show, :index, :destroy, :create, :new, :confirm_email]
    before_action :is_authenticated_user, only: [:edit, :update, :destroy]
    before_action :require_logout, only: [:new]
    
    def index
        @users = User.all();
        # @users = User.paginate(page: params[:page], per_page: 4)
    end

    def show
        # Creates instance variable with the value, and it will be available in htmo.erb view file.
        # @user = User.find(params[:id]);  # Will find Article with id of whatever is passed in params
        # @users = @user.articles.paginate(page: params[:page], per_page: 4);
    end

    def new
        @user = User.new();
    end

    def create
         # render plain: params[:user]

        # require the Top level keys of users and permits username, email and password from there
        values = params.require(:user).permit(:username, :email, :password, :admin); #White Listing
        @user = User.new(values);
        
        
        if @user.save()
            
            UserMailer.registration_confirmation(@user).deliver

            flash[:notice] = "Please confirm your email address to continue"
            redirect_to root_path

            # flash[:notice] = "Thanks for joining! Welcome #{@user.username}!"
            # session[:user_id] = @user.id;
            # redirect_to root_path
        else
            flash[:alert] = "Ooooppss, something went wrong!"
            render 'new'
         end
    end

    def confirm_email

        user = User.find_by_confirm_token(params[:id])

        if user
          user.email_activate
          flash[:notice] = "Welcome to the OpenShop! Your email has been confirmed.
          Please sign in to continue."
          redirect_to login_url
        else
          flash[:alert] = "Sorry. User does not exist"
          redirect_to root_url
        end
    end

    def edit
        # @user = User.find(params[:id]);
    end

    def update
         # render plain: params[:article]

        # require the Top level keys of users and permits username, email and password from there
        values = params.require(:user).permit(:username, :email, :password, :admin); #White Listing

        # @user = User.find(params[:id]);

        # @article.user = User.first;

        if @user.update(values)
            flash[:notice] = "Changes saved to Profile successfully!"
            # render plain: @user.inspect
            redirect_to user_path(@user);     # WOWWW! It's defining paths automatically. 
            # redirect_to @article;     # Same effect... JUST WOWWWW!!!
        else
            render 'edit'
         end
    end

    def destroy
        @user.destroy();
        session[:user_id] = nil;
        flash[:notice]= "Account and all associated Articles Deleted.";
        redirect_to root_path;
    end

    private
    def set_user
        @user = User.find(params[:id]);  # Will find Article with id of whatever is passed in params
        
    end

    def is_authenticated_user
        if current_user != @user
            flash[:alert] = "You Can only Edit your Account.";
            redirect_to @user;
        end
    end

    def is_Admin
        if !current_user.admin?
            flash[:alert] = "Only Admin can perform this action.";
            redirect_to @user;
        end
    end

end

app/views/users/_form.html.erb
<div class="container d-flex justify-content-center align-items-center mt-3">
    <div class="row">
        <div class="col-sm-5 col-md-6 offset-md-3">

            <%= render('shared/errors', obj: @user)%>

            <div class="card shadow">
                <%# <img src="https://images.unsplash.com/photo-1571863533956-01c88e79957e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1267&q=80" alt="" class="card-img-top" /> %>
                <%# https://images.unsplash.com/photo-1528832253532-9c22462c0086?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=747&q=80 %>
                <img src="https://images.unsplash.com/photo-1472851294608-062f824d29cc?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=750&q=80" alt="" height="80%" class="card-img-top" />
                <div class="card-body">
                    <h3 class="card-title"> <%= @user.new_record? ? "Signing Up" :"Edit Profile"%> </h3>

                    <%= form_with(model: @user, class:"validfated-form", local: true )  do |f| -%>

                    <%# <form action="/login" method="post" class="validfated-form" nonvalidate> %>
                        <div class="mb-3">
                            <%# <label class="form-label" for="username">Username</label> %>
                            <%= f.label :username, class: "form-label" -%>
    
                            <%# <input class="form-control" id="username" name="username" type="text" autofocus required> %>
                            <%= f.text_field :username, class: "form-control shadow rounded", placeholder:"username" -%>
                            
                            <div class="valid-feedback">Looks Good!</div>
                        </div>

                        <div class="mb-3">
                            <%# <label class="form-label" for="password">Password</label> %>
                            <%= f.label :email, class: "form-label" -%>

                            <%# <input class="form-control" id="password" name="password" type="password" required> %>
                            <%= f.email_field :email, class: "form-control shadow rounded", placeholder:"Enter Email" -%>
                            
                            
                            <div class="valid-feedback">Looks Good!</div>
                        </div>
        
                        <div class="mb-3">
                            <%# <label class="form-label" for="password">Password</label> %>
                            <%= f.label :password, class: "form-label" -%>

                            <%# <input class="form-control" id="password" name="password" type="password" required> %>
                            <%= f.password_field :password, class: "form-control shadow rounded", placeholder:"Enter Password" -%>
                            
                            
                            <div class="valid-feedback">Looks Good!</div>
                        </div>

                        <div class="mb-3">
                            <%= f.label "Creating Admin Profile?", class: "form-label" -%>
                            
                            <%= f.select(:admin, ['true', 'false'], {}, { class: "custom-select form-control shadow rounded" }) %>
                        </div>

                        <%= f.submit(@user.new_record? ? "Sign Up" :"Update Profile", class: "btn btn-success btn-block")-%>

                    <% end %>
                </div>
            </div>

        </div>
    </div>
</div>

app/views/users/_users.html.erb
 <div class="container content_container">
        <div class="row justify-content-md-center">
            <% @users.each do |user| %>
                <div class="col-8 mt-4">
                    <div class="card text-center shadow mb-5 bg-white rounded">
                        <div class="card-header font-italic">
                            <%= user.admin? ? "Admin" : "Csutomer"%> 
                        </div>
                        <div class="card-body">
                            <h5 class="card-title"><%= link_to user.username, product_path(user), class: 'text-success'%></h5>
                            <p class="card-text"><b>Email: </b><%=user.email%></p>

                            <a href="<%=user_path(user) %>" class="btn btn-outline-success ">View Profile</a>
                        
                        </div>
                        <div class="card-footer text-muted">
                            <small>
                                Created <%= time_ago_in_words(user.created_at)%> ago,
                                Edited <%= time_ago_in_words(user.updated_at)%> ago
                            </small>
                        </div>
                    </div>
                </div>
            <% end -%>
        </div>
    </div>

app/views/users/edit.html.erb
<%= render 'layouts/navigation'%> 

<%= render('form')%>

app/views/users/index.html.erb
<%= render 'layouts/navigation'%> 

<div id="page-content">
    <h1 class="text-center mt-2">Showing All Users</h1>

    <%= render 'users'%> 
   
</div>

app/views/users/new.html.erb
<div class="container d-flex justify-content-center align-items-center mt-3">
    <div class="row">
        <div class="col-md-4 offset-md-4">

            <div class="card shadow">
            <%# <img src="https://images.unsplash.com/photo-1571863533956-01c88e79957e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1267&q=80" alt="" class="card-img-top" /> %>
            <%# https://images.unsplash.com/photo-1528832253532-9c22462c0086?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=747&q=80 %>
            <img src="https://images.unsplash.com/photo-1472851294608-062f824d29cc?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=750&q=80" alt="" height="80%" class="card-img-top" />
                <div class="card-body">
                    <h3 class="card-title">Sign Up</h3>
                    <%= form_with(model: @user, class:"validfated-form", local: true )  do |f| -%>
            
                    <%# <form action="/login" method="post" class="validfated-form" nonvalidate> %>
                        <div class="mb-3">
                            <%# <label class="form-label" for="username">Username</label> %>
                            <%= f.label :username, class: "form-label" -%>

                            <%# <input class="form-control" id="username" name="username" type="text" autofocus required> %>
                            <%= f.text_field :username, class: "form-control shadow rounded", placeholder:"username" -%>
                            
                            <div class="valid-feedback">Looks Good!</div>
                        </div>

                        <div class="mb-3">
                            <%# <label class="form-label" for="password">Password</label> %>
                            <%= f.label :email, class: "form-label" -%>

                            <%# <input class="form-control" id="password" name="password" type="password" required> %>
                            <%= f.email_field :email, class: "form-control shadow rounded", placeholder:"Enter Email" -%>
                            
                            
                            <div class="valid-feedback">Looks Good!</div>
                        </div>
        
                        <div class="mb-3">
                            <%# <label class="form-label" for="password">Password</label> %>
                            <%= f.label :password, class: "form-label" -%>

                            <%# <input class="form-control" id="password" name="password" type="password" required> %>
                            <%= f.password_field :password, class: "form-control shadow rounded", placeholder:"Enter Password" -%>
                            
                            
                            <div class="valid-feedback">Looks Good!</div>
                        </div>
                        <button class="btn btn-success btn-block">Sign In</button>



                    <% end %>
                </div>
            </div>

        </div>
    </div>
</div>

app/views/users/show.html.erb
<%= render 'layouts/navigation'%> 

<div id="page-content">
    <h1 class="text-center mt-1"><%= @user.username %>'s Profile</h1>

    <div class="container content_container mt-3">

        
        
        <div class="row justify-content-md-center">
            
            <div class="col-8 mt-1">
                <img src="https://bootdey.com/img/Content/avatar/avatar7.png" 
                class="img-fluid rounded shadow mx-auto d-block" width="25%" height="25%"  alt="...">

                <div class="card text-center shadow mb-5 bg-white rounded">
                    
                    <div class="card-body">
                         <ul class="list-group list-group-flush">

                            <li class="list-group-item text-muted">
                                <% if @user.admin? %>
                                    Admin
                                <% else %>
                                    Customer
                                <% end %>
                                </li>
                            
                            <li class="list-group-item"><b>Email: </b> <%= @user.email %> </li>
                            
                        </ul>

                        <% if logged_in? && current_user.id == @user.id %>
                            <%= link_to "Edit Your Profile", edit_user_path(@user), class: "btn btn-outline-info" %>

                            <%= link_to 'Delete Profile',user_path(@user), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you Sure?"} %>
                        <% end %>
                    </div>
                    <div class="card-footer text-muted">
                        <small>
                            Joined <%= time_ago_in_words(@user.created_at)%> ago
                        </small>
                    </div>
                </div>
            </div>
        </div>
    </div>
<</div>