config/routes.rb
Rails.application.routes.draw do
  # get 'landing/index'
  root 'pages#home'

  get 'about', to: 'pages#about'

  get 'signup', to: 'users#new'
  
  resources :users, except: [:new]
  resources :products
  resources :categories

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'chat', to: 'chats#index'
  post 'message', to: "messages#create"

  mount ActionCable.server, at: '/cable'

  get 'landing/index'

  resources :carts
  resources :items

  post '/add_to_cart/:product_id', to: 'carts#add_to_cart'
  post 'items/:id/add' => "items#add_quantity", as: "item_add"
  post 'items/:id/reduce' => "items#reduce_quantity", as: "item_reduce"

  resources :orders, only: [:index, :show, :new, :create]

  resources :users do
    member do
      get :confirm_email
    end
  end

end

app/models/Cart.rb
class Cart < ApplicationRecord

    belongs_to :user
    # has_many :items

    has_many :items, dependent: :destroy
    has_many :products, through: :items

    # LOGIC
    def sub_total
        sum = 0
        self.items.each do |item|
        sum+= item.total_price
        end
        return sum
    end

    # def add_item(product_id)
    #     item = Item.find_by({product_id: product_id})
    #     if item
    #         # increase the quantity of product in cart
    #         item.quantity = item.quantity + 1
    #         item.save()
    #     else

    #         # product does not exist in cart
    #         # byebug;
    #         current_cart.items << Item.new(product_id: product_id, quantity: 1);
    #         # new_item.save()
    #         # end
    #     end
    #     # save
    # end
      

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :set_cart, only: [:show, :edit, :update, :destroy]
    before_action :require_login, except: [:show, :index]
    before_action :is_Admin, only: [:edit, :update, :destroy]

    def index
        @carts = Cart.all();
        # @users = User.paginate(page: params[:page], per_page: 4)
    end

    def show
        # byebug;
        # Creates instance variable with the value, and it will be available in htmo.erb view file.
        # @product = Product.find(params[:id]);  # Will find Article with id of whatever is passed in params
        # @articles = @user.articles.paginate(page: params[:page], per_page: 4);
    end

    def add_to_cart

        # Find associated product and current cart
        chosen_product = Product.find(params[:product_id])
        # current_cart = @current_cart

        # If cart already has this product then find the relevant line_item and iterate quantity otherwise create a new line_item for this product
        if current_cart.products.include?(chosen_product)
            # Find the line_item with the chosen_product
            @item = current_cart.items.find_by(:product_id => chosen_product)
            # Iterate the line_item's quantity by one
            @item.quantity += 1
        else
            @item = Item.new({quantity: 1});
            @item.cart = current_cart
            @item.product = chosen_product
        end

        # Save and redirect to cart show path
        @item.save
        redirect_to cart_path(current_cart)

        # byebug;
        # alert("Adding to Cart");
        # render plain: params[:product_id]

        # session[:cart_id] = nil;

        # add_item(params[:product_id])
        # current_cart.user = current_user;
        
        # flash.now[:notice] = "Product has been added to Cart successfully!"
        # redirect to shopping cart or whereever
    end

    # def new
    #     @cart = Cart.new();
    # end

    # def create
    #     # render plain: params[:article]

    #     # require the Top level keys of article and permits title and description from there
    #     # values = params.require(:article).permit(:title, :description); #White Listing
    #     @cart = Cart.new(white_listed_params);
        
    #     # img_values = params.require(:article).permit(:image);
    #     # img_values.foreach do|img|
    #     #     image = Image.new(img);
    #     #     prouct.build_image(image);
    #     # end
    #     # # @article.user = current_user;

    #     if @cart.save()
    #         flash[:notice] = "art has been created successfully!"
    #         # render plain: @article.inspect
    #         redirect_to cart_path(@cart);     # WOWWW! It's defining paths automatically. 
    #         # redirect_to @article;     # Same effect... JUST WOWWWW!!!
    #     else
    #         render 'new'
    #      end
    # end

    # def edit 
    #     # @article = Article.find(params[:id]);  # Will find Article with id of whatever is passed in params
    # end

    # def update 
    #     # @article = Article.find(params[:id]);  # Will find Article with id of whatever is passed in params
    #     # values = params.require(:article).permit(:title, :description);     #White Listing
    #      if @cart.update(white_listed_params);
    #         flash[:notice] = "Article is Updated successfully!"
    #         # render plain: @article.inspect
    #         redirect_to cart_path(@cart);     # WOWWW! It's defining paths automatically. 
    #         # redirect_to @article;     # Same effect... JUST WOWWWW!!!
    #     else
    #         render 'edit'
    #      end
    # end

    # def destroy
    #     # @article = Article.find(params[:id]);  # Will find Article with id of whatever is passed in params
    #     @cart.destroy;
    #     redirect_to carts_path
    # end

    private
    def set_cart
        @cart = Cart.find(params[:id]);  # Will find Article with id of whatever is passed in params
    end

    def white_listed_params
        params.require(:cart).permit(:name, :price, :description, category_ids: []);
    end

    def is_Admin
        if !current_user.admin?
            flash[:alert] = "Only Admin can perform this action.";
            redirect_to @cart;
        end
    end

    def add_item(product_id)
        item = Item.find_by({product_id: product_id})
        if item
            # increase the quantity of product in cart
            item.quantity = item.quantity + 1
            item.save()
        else
            # product does not exist in cart
            # byebug;
            current_cart.items << Item.new(product_id: product_id, quantity: 1);
            # new_item.save()
            # end
        end
        # save
    end

 
end

app/views/carts/show.html.erb
<%= render 'layouts/navigation'%>

<%# <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css"> %>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

<div class="container content_container">
	<table id="cart" class="table table-hover table-condensed">
        <thead>
            <tr>
                <th style="width:50%">Product</th>
                <th style="width:10%">Price</th>
                <th style="width:8%">Quantity</th>
                <th style="width:22%" class="text-center">Subtotal</th>
                <th style="width:10%"></th>
            </tr>
        </thead>
        <tbody>
            <% current_cart.items.each do |item| %>
                <tr>
                    <td data-th="Product">
                        <div class="row">
                            <div class="col-sm-2 hidden-xs mx-auto"><img src="https://images.unsplash.com/photo-1590992754618-1490fd4f435a?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=644&q=80" alt="..." class="img-responsive img-fluid"/></div>
                            <div class="col-sm-8 mx-auto">
                                <h4 class="nomargin"> <%= item.product.name%> </h4>
                                <p> <%= truncate(item.product.description, length: 50)%> </p>
                            </div>
                        </div>
                    </td>
                    <td data-th="Price"><%= number_to_currency(item.product.price) %></td>
                    <td data-th="Quantity">
                        <p><%= item.quantity %></p>
                        <span  class='text-center'>
                            <%= link_to '<button class="btn btn-danger btn-sm "><i class= "fa fa-minus" aria-hidden="true"></i></button>'.html_safe, item_reduce_path(:id => item), method: :post%>
                        </span>
                        
                        <span class='text-center'>
                            <%= link_to '<button class="btn btn-success btn-sm"><i class= "fa fa-plus" aria-hidden="true"></i></button>'.html_safe, item_add_path(:id => item), method: :post%>
                        </span>

                    </td>
                    <td data-th="Subtotal" class="text-center"> <%= number_to_currency(item.total_price) %></td>

                    <td class="actions" data-th="">
                        <button class="btn btn-info btn-sm"><i class="fa fa-refresh"></i></button>
                     								
                        <%= link_to '<button class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i></button>'.html_safe, item_path(item), method: :delete%>

                    </td>
                </tr>
            <% end %>
             
        <%# <div class="col-sm-2 hidden-xs mx-auto"><img src="http://placehold.it/100x100" alt="..." class="img-responsive img-fluid"/></div> %>

        </tbody>
        <tfoot>
            <%# <tr class="visible-xs">
                <td class="text-center"><strong>Total 1.99</strong></td>
            </tr> %>
            <tr>
                <td><a href="/products" class="btn btn-warning"><i class="fa fa-arrow-circle-left"></i> Continue Shopping</a></td>
                <td colspan="2" class="hidden-xs"></td>
                <td class="hidden-xs text-center"><strong>Total <%= number_to_currency(current_cart.sub_total) %> </strong></td>
                
                <td><a href="/orders/new" class="btn btn-success btn-block">Checkout <i class="fa fa-arrow-circle-right"></i></a></td>
            </tr>
        </tfoot>
    </table>
</div>