config/routes.rb
Rails.application.routes.draw do
  # get 'landing/index'
  root 'pages#home'

  get 'about', to: 'pages#about'

  get 'signup', to: 'users#new'
  
  resources :users, except: [:new]
  resources :products
  resources :categories

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'chat', to: 'chats#index'
  post 'message', to: "messages#create"

  mount ActionCable.server, at: '/cable'

  get 'landing/index'

  resources :carts
  resources :items

  post '/add_to_cart/:product_id', to: 'carts#add_to_cart'
  post 'items/:id/add' => "items#add_quantity", as: "item_add"
  post 'items/:id/reduce' => "items#reduce_quantity", as: "item_reduce"

  resources :orders, only: [:index, :show, :new, :create]

  resources :users do
    member do
      get :confirm_email
    end
  end

end

app/models/Product.rb
class Product < ApplicationRecord

    # "dependent: :destroy" to destroy dependents.
    # has_many :images, dependent: :destroy

    # serialize :category

    # after_initialize do |product|
    #     product.category= [] if patient.category == nil
    # end

    has_many :product_categories
    has_many :categories, through: :product_categories

    # has_many :items
    # has_and_belongs_to_many :object, join_table: "table_name", foreign_key: "object_id"


    has_many :item_products
    has_many :items, through: :item_products

    validates :name, presence: true, length: { minimum: 1, maximum: 35 }

    validates :price, presence: true
                # , 
                # numericality: { only_integer: true },
                # value: { minimum: 1}
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :set_product, only: [:show, :edit, :update, :destroy]
    before_action :require_login, except: [:show, :index]
    before_action :is_Admin, only: [:edit, :update, :destroy, :new, :create]

    def index
        @products = Product.all();
        # @users = User.paginate(page: params[:page], per_page: 4)
    end

    def show
        # Creates instance variable with the value, and it will be available in htmo.erb view file.
        # @product = Product.find(params[:id]);  # Will find Article with id of whatever is passed in params
        # @articles = @user.articles.paginate(page: params[:page], per_page: 4);
    end


    def new
        @product = Product.new();
    end

    def create
        # render plain: params[:article]

        # require the Top level keys of article and permits title and description from there
        # values = params.require(:article).permit(:title, :description); #White Listing
        @product = Product.new(white_listed_params);
        
        # img_values = params.require(:article).permit(:image);
        # img_values.foreach do|img|
        #     image = Image.new(img);
        #     prouct.build_image(image);
        # end
        # # @article.user = current_user;

        if @product.save()
            flash[:notice] = "Product has been created successfully!"
            # render plain: @article.inspect
            redirect_to product_path(@product);     # WOWWW! It's defining paths automatically. 
            # redirect_to @article;     # Same effect... JUST WOWWWW!!!
        else
            render 'new'
         end
    end

    def edit 
        # @article = Article.find(params[:id]);  # Will find Article with id of whatever is passed in params
    end

    def update 
        # @article = Article.find(params[:id]);  # Will find Article with id of whatever is passed in params
        # values = params.require(:article).permit(:title, :description);     #White Listing
         if @product.update(white_listed_params);
            flash[:notice] = "Article is Updated successfully!"
            # render plain: @article.inspect
            redirect_to product_path(@product);     # WOWWW! It's defining paths automatically. 
            # redirect_to @article;     # Same effect... JUST WOWWWW!!!
        else
            render 'edit'
         end
    end

    def destroy
        # @article = Article.find(params[:id]);  # Will find Article with id of whatever is passed in params
        @product.destroy;
        redirect_to products_path
    end

    private
    def set_product
        @product = Product.find(params[:id]);  # Will find Article with id of whatever is passed in params
    end

    def white_listed_params
        params.require(:product).permit(:name, :price, :description, category_ids: []);
    end

end

app/views/products/_form.html.erb
<div class="container d-flex justify-content-center align-items-center mt-3">
    <div class="row">
        <div class="col-sm-6 col-md-8 offset-sm-3">

            <div class="card shadow">
                <img src="https://neilpatel.com/wp-content/uploads/2017/08/How-To-Generate-Buzz-When-You-Launch-a-New-Product.jpg" alt="" height="80%" class="card-img-top" />
                <div class="card-body">
                    <h3 class="card-title text-center">New Product</h3>

                     <%= form_with(model: @product, method: 'POST', class:"validfated-form", local: true  )  do |f| -%>
                        <div class="mb-3">
                            <%= f.label :name, class: "form-label" -%>
                            <%= f.text_field :name, class: "form-control shadow rounded", placeholder:"Name" -%>
                            <div class="valid-feedback">Looks Good!</div>
                        </div>
                        
                        <div class="mb-3">
                            <%= f.label :price , class: "form-label" -%>

                            <%# <label class="form-label" for="price">Product Price</label> %>
                            <div class="input-group mb-3">
                                <span class="input-group-text" id="price-tag">$</span>
                                <%# <input id="price" type="text" class="form-control" name="price" placeholder="0.00" aria-label="Price" aria-describedby="price-tag" required> %>
                                <%= f.number_field :price, class: "form-control shadow rounded", placeholder:"0.00" -%>
                                
                                <div class="valid-feedback">
                                    Looks Good!
                                </div>
                            </div>
                        </div>
                    
                        <div class="mb-3">
                            <%= f.label :description, class: "form-label" -%>

                            <%= f.text_area :description, class: "form-control shadow rounded", placeholder:"Tell About the Product..." -%>
                            
                            <div class="valid-feedback">Looks Good!</div>
                        </div>

                        <div class="mb-3">
                            <%= f.label :category, class: "form-label" -%>

                            <%= f.collection_select(:category_ids, Category.all, :id, :name,
                            {prompt: "Make Categories Selection:"}, 
                            { multiple: true, size:3 , class: "custom-select form-control shadow rounded"} 
                            )  %>

                            <div class="valid-feedback">Looks Good!</div>
                        </div>

                        <div class="mb-3">
                            <%= f.submit(@product.new_record? ? "Add Product" :"Save Changes", class: "btn btn-success btn-block")-%>
                        </div>
                    <%# </form> %>
                    <% end %>
                </div>

            </div>
        </div>
    </div>
</div>

app/views/products/_product_carousel.html.erb
<div id="categories_carousel" class="carousel slide z-depth-1-half" data-ride="carousel">

    <ol class="carousel-indicators">
    <li data-target="#categories_carousel" data-slide-to="0" class="active"></li>
    <li data-target="#categories_carousel" data-slide-to="1"></li>
    <li data-target="#categories_carousel" data-slide-to="2"></li>
  </ol>

    <div class="carousel-inner">

        <div class="carousel-item active">

            <img src="https://cdn.britannica.com/22/75922-050-D3982BD0/flowers-fruits-garden-strawberry-plant-species.jpg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block text-black-50">
                    <h5><%= @product.name%></h5>
                    <%# <p>Some representative placeholder content for the first slide.</p> %>
                </div>
            </a>
        </div>

        <div class="carousel-item">
            
            <img src="https://images.unsplash.com/photo-1519180392711-496e450edf6a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=750&q=80" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block text-black-50">
                    <h5><%= @product.name%></h5>
                    <%# <p>Some representative placeholder content for the first slide.</p> %>
                </div>
            </a>
        </div>

        <div class="carousel-item">
            <img src="https://shellsfeed.com/wp-content/uploads/2018/10/feature_image.jpg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block text-black-50">
                    <h5><%= @product.name%></h5>
                    <%# <p>Some representative placeholder content for the first slide.</p> %>
                </div>
            </a>
        </div>

    </div>

    <button class="carousel-control-prev" type="button" href="#categories_carousel" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" href="#categories_carousel" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

app/views/products/_products.html.erb
 <div class="container content_container">
            <% @products.each do |product| %>
            
                <div class="card text-center shadow mb-5 bg-white rounded">
                    <div class="row justify-content-md-center">
                        <div class="col-md-4 my-auto">
                            <img class="img-fluid" src="https://cdn.britannica.com/22/75922-050-D3982BD0/flowers-fruits-garden-strawberry-plant-species.jpg" alt="">
                        </div>
                        <div class="col-6 mt-4">
                            <div class="card-header font-italic">
                                <b>Price: </b>$<%=product.price%> 
                            </div>
                            <div class="card-body">
                                <h5 class="card-title"><%= link_to product.name, product_path(product), class: 'text-success'%></h5>
                                <p class="card-text"><b>Price: </b>$<%=product.price%></p>

                                <a href="<%=product_path(product) %>" class="btn btn-outline-info ">Product Details</a>
                            </div>
                            <div class="card-footer text-muted">
                                <small>
                                    Created <%= time_ago_in_words(product.created_at)%> ago,
                                    Edited <%= time_ago_in_words(product.updated_at)%> ago
                                </small>
                            </div>
                        </div>
                    </div>
                </div>

            <% end -%>
    </div>

app/views/products/edit.html.erb
<%= render 'layouts/navigation'%>

<div class="container mt-4">
    <div class="row">
        <h1 class="text-center">Edit Product</h1>
        <div class="col-6 offset-3">

            <%# <form action="/products" method="POST" class="validated-form" enctype="multipart/form-data" novalidate > %>
            <form action="/products/<%= @product._id%>?_method=PATCH" method="POST" class="validated-form" enctype="multipart/form-data" novalidate >
            
                <div class="mb-3">
                    <label class="form-label" for="name">Name</label>
                    <input class="form-control" id="name" name="name" type="text" required>
                    <div class="valid-feedback">Looks Good!</div>
                </div>
                <%# <div class="mb-3">
                    <label class="form-label" for="location">Location</label>
                    <input class="form-control" id="location" name="location" type="text" required>
                    <div class="valid-feedback">Looks Good!</div>
                </div> %>

                <div class="mb-3">
                    <label class="form-label" for="price">Product Price</label>
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="price-tag">$</span>
                        <input id="price" type="text" class="form-control" name="price" placeholder="0.00" aria-label="Price" aria-describedby="price-tag" required>
                        <div class="valid-feedback">
                            Looks Good!
                        </div>
                    </div>
                </div>

                <div class="mb-3">
                    <label class="form-label" for="description">Description</label>
                    <textarea class="form-control" id="description" name="description" type="text" required></textarea>
                    <div class="valid-feedback">Looks Good!</div>
                </div>

                <div class="mb-3">
                    <label for="">Upload Images</label>
                    <div class="form-file custom-file">
                        <input type="file" class="form-file-input" id="image" name="image" multiple>
                        <label for="image" class="form-file-label custom-file-label">
                            <span class="form-file-text">Choose Image(s)...</span>
                        </label>
                    </div>
                </div>

                </div> -->
                <div class="mb-3">
                    <button class="btn btn-success btn-block" id="new_product_btn">Edit Product</button>
                </div>
            </form>
            
        </div>

    </div>

</div>

app/views/products/index.html.erb
<%= render 'layouts/navigation'%> 

<div id="page-content">
    <h1 class="text-center my-2">All Products</h1>


    <%= render 'products'%> 
   
</div>

app/views/products/new.html.erb
<%= render 'layouts/navigation'%>

<%= render 'form'%>

app/views/products/show.html.erb
<%= render 'layouts/navigation'%> 

<div id="page-content">
    <h1 class="text-center mt-1"><%= @product.name%></h1>

    <div class="container mt-3">
        
        <div class="row justify-content-md-center">
            <div class="col-7 mt-1">
                <%= render 'product_carousel'%>
            </div>
            
            <div class="col-5 mt-1">
                <div class="card text-center shadow mb-5 bg-white rounded">
           
                    <div class="card-body">
                         <ul class="list-group list-group-flush">
                            <li class="list-group-item text-muted"><%= @product.description %> </li>
                            <li class="list-group-item"><b>Price: $</b><%=@product.price%></li>
                            <% if @product.categories.any? %>
                                    <li class="list-group-item">
                                <% @product.categories.each do |category|%>
                                        <%= link_to category.name, category_path(category), class:"badge badge-pill badge-info"%>
                                <% end %>
                                    </li>
                            <% end %>
                            
                        </ul>
                        <% if logged_in? && current_user.admin? %>
                            <a href="<%= edit_product_path(@product) %>" class="btn btn-outline-primary">Edit</a>
                            <%= link_to "Delete", product_path(@product), method: :delete, data: {confirm: 'Are You Sure?'}, class: "btn btn-outline-danger"%>
                        <% end %>


                        <%= link_to "Add to Cart ", "/add_to_cart/#{@product.id}", class: "btn btn-lg btn-success", method: "POST" %> 
                       
                        <%# <button class="btn btn-lg btn-success" >

                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-check-fill" viewBox="0 0 16 16">
                                <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm-1.646-7.646-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L8 8.293l2.646-2.647a.5.5 0 0 1 .708.708z"/>
                            </svg>
                        </button> %>
                    </div>
                    <div class="card-footer text-muted">
                        <small>
                            Created <%= time_ago_in_words(@product.created_at)%> ago,
                            Edited <%= time_ago_in_words(@product.updated_at)%> ago
                        </small>
                    </div>
                </div>
            </div>
        </div>
    </div>
<</div>