config/routes.rb
Rails.application.routes.draw do
  # get 'landing/index'
  root 'pages#home'

  get 'about', to: 'pages#about'

  get 'signup', to: 'users#new'
  
  resources :users, except: [:new]
  resources :products
  resources :categories

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'chat', to: 'chats#index'
  post 'message', to: "messages#create"

  mount ActionCable.server, at: '/cable'

  get 'landing/index'

  resources :carts
  resources :items

  post '/add_to_cart/:product_id', to: 'carts#add_to_cart'
  post 'items/:id/add' => "items#add_quantity", as: "item_add"
  post 'items/:id/reduce' => "items#reduce_quantity", as: "item_reduce"

  resources :orders, only: [:index, :show, :new, :create]

  resources :users do
    member do
      get :confirm_email
    end
  end

end

app/views/layouts/_cart_button.html.erb
<%# <div class="rounded-circle btn btn-danger"> %>
    <span id='cart_div' class="float-right  mt-2 mr-1">
        <a href="/carts/<%=current_cart.id%>" class="btn  btn-bg btn-dark"> Cart
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-check-fill" viewBox="0 0 16 16">
            <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm-1.646-7.646-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L8 8.293l2.646-2.647a.5.5 0 0 1 .708.708z"/>
        </svg> 
        <% if current_cart.items.count > 0%>
            <span class="badge rounded-pill bg-danger"> <%= current_cart.items.count%> </span>
        <% end %>
        </a>
    </span>
<%# </div> %>

app/views/layouts/_categories_carousel.html.erb
<div id="categories_carousel" class="carousel slide z-depth-1-half" data-ride="carousel">

    <ol class="carousel-indicators">
    <li data-target="#categories_carousel" data-slide-to="0" class="active"></li>
    <li data-target="#categories_carousel" data-slide-to="1"></li>
    <li data-target="#categories_carousel" data-slide-to="2"></li>
  </ol>

    <div class="carousel-inner">

        <div class="carousel-item active">
            <a href="<%= category_path(@category)%>">

            <img src="https://i.ytimg.com/vi/PRoHErzVPyU/maxresdefault.jpg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block text-black-50">
                    <h5><%= @category.name%></h5>
                    <%# <p>Some representative placeholder content for the first slide.</p> %>
                </div>
            </a>
        </div>

        <div class="carousel-item">
            <a href="<%= category_path(@category)%>">
            
            <img src="https://growyourownfood.biz/wp-content/uploads/2020/10/proud-gardener-royalty-free-image-539829042-1555499812-1.jpg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block text-black-50">
                    <h5><%= @category.name%></h5>
                    <%# <p>Some representative placeholder content for the first slide.</p> %>
                </div>
            </a>
        </div>

        <div class="carousel-item">
            <a href="<%= category_path(@category)%>">
            <img src="https://gardenseason.com/wp-content/uploads/2019/09/gardener-planting-flowers-gardening-skills-ss-featured.jpg" class="d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block text-black-50">
                    <h5><%= @category.name%></h5>
                    <%# <p>Some representative placeholder content for the first slide.</p> %>
                </div>
            </a>
        </div>

    </div>

    <%# <a class="carousel-control-prev" href="#categories_carousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#categories_carousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a> %>

    <button class="carousel-control-prev" type="button" href="#categories_carousel" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" href="#categories_carousel" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

app/views/layouts/_footer.html.erb
<%# 
<footer class="mt-auto text-white-50">
    <p>&copy; 2021 </p>
</footer> %>

<div class="mt-auto custom_footer navbar-fixed-bottom">
    <footer class="footer bg-dark py-3 mt-auto" >
        <div class="container">
            <span class="text-muted"> &copy;<i>Open</i>Shop 2021 <br>
                <%# By <a id="author_link" href="https://twitter.com/HamzaRandhaawa">@HamzaNoorRandhawa</a>     %>
            </span>
        </div>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
  <% if(flash.notice) %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <strong>Success!</strong>
        <%= flash.each do|name, msg| %>
            <%= msg %>
        <% end -%>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <% end -%>

  <% if(flash.alert) %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <strong>Alert!</strong>
        <%= flash.each do|name, msg| %>
            <%= msg %>
        <% end -%>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end -%>

</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%# <a class="navbar-brand" id="logo" href="#">ALPHA BLOG</a> %>
    <a href="<%= root_path %>" class= "navbar-brand" id= 'logo' ><span id="open">Open</span><span id="shop">Shop</span></a>
    <button class="navbar-toggler bg-dark " type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <%# <a class="nav-link" href="#">Link</a> %>
                <%= link_to 'Users',users_path, class: "nav-link" %>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="/products" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Categories
                </a>

                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to 'All Categories', categories_path, class: "dropdown-item" %>
                    <% if logged_in? && current_user.admin?%>
                        <div class="dropdown-divider"></div>
                        <%= link_to 'New Category', new_category_path, class: "dropdown-item" %>
                    <% end %>
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="/products" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Products
                </a>

                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to 'All Products', products_path, class: "dropdown-item" %>
                    <% if logged_in? && current_user.admin?%>
                        <div class="dropdown-divider"></div>
                        <%= link_to 'New Product', new_product_path, class: "dropdown-item" %>
                    <% end %>
                </div>
            </li>

            <% if logged_in?%>
                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= "(Admin)" if current_user.admin?%>    <%= current_user.username %>
                </a>

                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to 'View Profile',user_path(current_user), class: "dropdown-item" %>

                    <%= link_to 'Edit Profile',edit_user_path(current_user), class: "dropdown-item" %>

                    <%= link_to 'Delete Profile',user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: {confirm: "Are you Sure?"} %>
                </div>
            </li>
            <% end %>
        </ul>

       <form class="form-inline d-flex my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      
        <ul class="navbar-nav ml-auto">
            <% if logged_in? %>
                    <li class="nav-item ">
                    <% if current_user.admin? %>
                        <%=link_to "Shipments", '/orders', class: 'nav-link' %>
                    <% else %>
                        <%=link_to "Your Shipments", '/orders', class: 'nav-link' %>
                    <% end %>

                    </li>

                <li class="nav-item ">
                    <% if current_user.admin? %>
                        <%= link_to "Help Customers", '/chat' ,class: 'nav-link' %>
                    <% else %>
                        <%= link_to "Contact Us", '/chat' ,class: 'nav-link' %>
                    <% end %>
                </li>

                <li class="nav-item ">
                    <%= link_to 'Log Out', logout_path, class: 'nav-link', method: :delete %>
                </li>
            <% else %>
                <li class="nav-item">
                    <%= link_to 'Log In', login_path, class: 'nav-link' %>
                </li>

                <li class="nav-item">
                    <%= link_to 'Sign Up', signup_path, class: 'nav-link' %>
                </li>

            <% end %>
        </ul>
    </div>
</nav>

<% if logged_in? %>
    <%= render 'layouts/cart_button'-%>
<% end %>
<%= render 'layouts/messages'-%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpenShop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



    <%= yield %>
    

  </body>

  <%= render 'layouts/footer'-%>
</html>

app/views/layouts/test.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar scroll</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Link
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Link</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>






<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <%# <a class="navbar-brand" id="logo" href="#">ALPHA BLOG</a> %>
        <%= link_to 'ShopIt', about_path, class: "navbar-brand", id: 'logo' %>
        <button class="navbar-toggler bg-dark " type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav mr-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">

                <li class="nav-item">
                    <%# <a class="nav-link" href="#">Link</a> %>
                    <%= link_to 'Users',users_path, class: "nav-link" %>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="/products" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Products
                    </a>

                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <%= link_to 'All Products', products_path, class: "dropdown-item" %>
                        <% if logged_in?%>
                            <div class="dropdown-divider"></div>
                            <%= link_to 'New Product', new_product_path, class: "dropdown-item" %>
                        <% end %>
                    </div>
                </li>

                <% if logged_in?%>
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%= "(Admin)" if current_user.admin?%>    <%= current_user.username %>
                    </a>

                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <%= link_to 'View Profile',user_path(current_user), class: "dropdown-item" %>

                        <%= link_to 'Edit Profile',edit_user_path(current_user), class: "dropdown-item" %>

                        <%= link_to 'Delete Profile',user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: {confirm: "Are you Sure?"} %>

                    </div>
                </li>
                <% end %>
            </ul>

            <form class="form-inline d-flex my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>

            <ul class="navbar-nav ml-auto">
                <% if logged_in? %>
                    <li class="nav-item ">
                        <%= link_to current_user.username, user_path(current_user), class: 'nav-link' %>
                    </li>
                    <li class="nav-item ">
                        <%= link_to 'Log Out', logout_path, class: 'nav-link', method: :delete %>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to 'Log In', login_path, class: 'nav-link' %>
                    </li>

                    <li class="nav-item">
                        <%= link_to 'Sign Up', signup_path, class: 'nav-link' %>
                    </li>

                <% end %>
            </ul>
        </div>
    </div>
</nav>